// <auto-generated> Generado por build/disenador_formatos/generar.py a partir de motor.cs y acciones.cs. No se edita a mano. </auto-generated>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace BrosLMV.Disenador
{
    static partial class Motor
    {
// ===================== motor de etiquetas (el mismo de «Generar documento (PDF)» y «PDF masivo») =====================
// Resuelve un formato HTML contra un documento: columnas de vwLBSDocDocumentPrint40-DocumentID, referencias del Diccionario de referencia (engAddendaFieldRef) y [Format(col,máscara)].
static System.Globalization.CultureInfo ciE = System.Globalization.CultureInfo.InvariantCulture;
static Dictionary<string, string> cacheRefE = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
static Dictionary<string, string> sqlRefsE = null;
static HashSet<string> refsExistenE = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
static HashSet<string> sinResolverE = new HashSet<string>();
static System.Text.RegularExpressions.Regex reFormatE = new System.Text.RegularExpressions.Regex(@"\[Format\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([^\)\]]+?)\s*\)\]", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
static System.Text.RegularExpressions.Regex reTagE = new System.Text.RegularExpressions.Regex(@"\[([A-Za-z_][A-Za-z0-9_]*)\]");

static List<Dictionary<string, object>> CargarFilasE(long doc)
{
    foreach (var tvf in new[] { "vwLBSDocDocumentPrint40-DocumentID", "vwLBSDocDocumentPrint33-DocumentID", "vwLBSDocDocumentPrint-DocumentID" })
    {
        try { var f = ctx.Query("SELECT * FROM dbo.[" + tvf + "](" + doc + ")"); if (f.Count > 0) return f; } catch { }
    }
    return new List<Dictionary<string, object>>();
}
static string ResolverRefE(string clave, long doc, long item)
{
    string ck = clave + "|" + doc + "|" + item;
    if (cacheRefE.TryGetValue(ck, out var hit)) return hit;
    string val = "";
    try
    {
        if (sqlRefsE == null)
        {
            sqlRefsE = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var rr in ctx.Query("SELECT FieldRefKey, SQL FROM engAddendaFieldRef WHERE DeletedOn IS NULL")) sqlRefsE[S(rr["FieldRefKey"])] = S(rr["SQL"]);
        }
        if (sqlRefsE.ContainsKey(clave))
        {
            refsExistenE.Add(clave);
            string sql = sqlRefsE[clave];
            if (sql.Trim().Length > 0)
            {
                sql = sql.Replace("{DocumentID}", doc.ToString()).Replace("{DocumentItemID}", item.ToString());
                var ov = ctx.Scalar(sql);
                val = ov == null || ov is DBNull ? "" : (ov is DateTime dref ? dref.ToString("dd/MM/yyyy") : Convert.ToString(ov, ciE));
            }
        }
    }
    catch { val = ""; }
    cacheRefE[ck] = val;
    return val;
}
static string FmtValorE(object ov) => ov == null || ov is DBNull ? "" : (ov is DateTime dt ? dt.ToString("dd/MM/yyyy") : Convert.ToString(ov, ciE));
static string ResolverE(string txt, Dictionary<string, object> fila, long doc, long item)
{
    txt = reFormatE.Replace(txt, m =>
    {
        string col = m.Groups[1].Value, mask = m.Groups[2].Value.Trim();
        object raw = fila != null && fila.ContainsKey(col) ? fila[col] : (object)ResolverRefE(col, doc, item);
        if (raw == null || raw is DBNull || Convert.ToString(raw) == "") return "";
        double dv;
        if (double.TryParse(Convert.ToString(raw, ciE), System.Globalization.NumberStyles.Any, ciE, out dv))
        {
            try { return dv.ToString(mask, ciE); } catch { return dv.ToString("#,##0.00"); }
        }
        return Convert.ToString(raw);
    });
    txt = reTagE.Replace(txt, m =>
    {
        string tag = m.Groups[1].Value;
        if (tag == "QRBros" || tag == "QRPayload" || tag == "DesgloseImpuestos") return m.Value;
        if (fila != null && fila.ContainsKey(tag)) return System.Net.WebUtility.HtmlEncode(FmtValorE(fila[tag]));
        string viaRef = ResolverRefE(tag, doc, item);
        if (!string.IsNullOrEmpty(viaRef)) return System.Net.WebUtility.HtmlEncode(viaRef);
        if (!refsExistenE.Contains(tag)) sinResolverE.Add(tag);
        return "";
    });
    return txt;
}
static string IncrustarImagenesE(string html, string baseDir)
{
    return System.Text.RegularExpressions.Regex.Replace(html, "src\\s*=\\s*\"([^\"]+)\"", m =>
    {
        string src = m.Groups[1].Value;
        if (src.StartsWith("data:", StringComparison.OrdinalIgnoreCase) || src.StartsWith("http", StringComparison.OrdinalIgnoreCase)) return m.Value;
        string ruta = src;
        try { if (!Path.IsPathRooted(ruta)) ruta = Path.Combine(baseDir, src); } catch { }
        if (!File.Exists(ruta)) return "src=\"\"";
        string ext = Path.GetExtension(ruta).TrimStart('.').ToLowerInvariant(); if (ext == "jpg") ext = "jpeg";
        try { return "src=\"data:image/" + ext + ";base64," + Convert.ToBase64String(File.ReadAllBytes(ruta)) + "\""; } catch { return "src=\"\""; }
    }, System.Text.RegularExpressions.RegexOptions.IgnoreCase);
}
// Texto que codifica el QR: en un documento TIMBRADO, la URL de verificación del SAT; si no, un texto simple con RFC, folio, fecha y total
static string PayloadQrE(Dictionary<string, object> fila0, long doc, long item0)
{
    string payload = System.Net.WebUtility.HtmlDecode(ResolverE("[EmisorRfc]|[Serie][Folio]|[FechaDocumento]|[Format(Total,#,##0.00)] [Moneda]", fila0, doc, item0));
    string uuidQr = fila0.ContainsKey("Uuid") ? S(fila0["Uuid"]).Trim() : "";
    if (uuidQr.Length >= 32)
    {
        string sello = fila0.ContainsKey("selloCFD") ? S(fila0["selloCFD"]).Trim() : ""; double totQr;
        double.TryParse(fila0.ContainsKey("Total") ? S(fila0["Total"]) : "0", System.Globalization.NumberStyles.Any, ciE, out totQr);
        payload = "https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?id=" + uuidQr + "&re=" + S(fila0.ContainsKey("EmisorRfc") ? fila0["EmisorRfc"] : "") + "&rr=" + S(fila0.ContainsKey("ReceptorRfc") ? fila0["ReceptorRfc"] : "") +
            "&tt=" + totQr.ToString("0000000000.000000", ciE) + "&fe=" + (sello.Length >= 8 ? sello.Substring(sello.Length - 8) : sello);
    }
    return payload;
}
// Renglones de total por impuesto (IVA, IEPS y retenciones) como filas del bloque de totales
static string DesgloseHtmlE(long doc)
{
    var sbtx = new StringBuilder();
    try
    {
        foreach (var t in ctx.Query("SELECT TaxName, CAST(Retention AS INT) AS Ret, SUM(Amount) AS Monto FROM docDocumentTaxDetail WHERE DocumentID=" + doc +
            " GROUP BY TaxName, CAST(Retention AS INT) HAVING ABS(SUM(Amount)) > 0.005 ORDER BY CAST(Retention AS INT), TaxName"))
        {
            bool ret = Convert.ToInt32(t["Ret"]) == 1; double mt = Convert.ToDouble(t["Monto"], ciE);
            sbtx.Append("<div class=\"row keep\"><span class=\"k\">" + (ret ? "Ret. " : "") + System.Net.WebUtility.HtmlEncode(S(t["TaxName"])) + "</span><span class=\"v\">" + (ret ? "-" : "") + "$" + mt.ToString("#,##0.00", ciE) + "</span></div>");
        }
    }
    catch { }
    return sbtx.ToString();
}
// Valores de ejemplo para el DISEÑADOR: cada etiqueta con el valor que tiene en el documento elegido (los renglones, solo los primeros)
static Dictionary<string, object> ValoresDisenoE(string html, string[] tokensExtra, bool detalle, long doc, string baseDir)
{
    var reTok = new System.Text.RegularExpressions.Regex(@"\[(?:Format\(\s*[A-Za-z_][A-Za-z0-9_]*\s*,\s*[^\)\]]+?\s*\)|[A-Za-z_][A-Za-z0-9_]*)\]");
    var filas = CargarFilasE(doc);
    var fila0 = filas.Count > 0 ? filas[0] : new Dictionary<string, object>();
    Func<Dictionary<string, object>, long> itemDe = f => f.ContainsKey("DocumentItemID") && f["DocumentItemID"] != null && !(f["DocumentItemID"] is DBNull) ? Convert.ToInt64(f["DocumentItemID"]) : 0;
    var cabecera = new List<string>(); var banda = new List<string>();
    if (html != null && html != "")
    {
        string sinScripts = System.Text.RegularExpressions.Regex.Replace(html, @"<(script|style)\b[\s\S]*?</\1>", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        var mDet = System.Text.RegularExpressions.Regex.Match(sinScripts, @"<DETAIL>(.*?)</DETAIL>", System.Text.RegularExpressions.RegexOptions.IgnoreCase | System.Text.RegularExpressions.RegexOptions.Singleline);
        string fuera = mDet.Success ? sinScripts.Remove(mDet.Index, mDet.Length) : sinScripts;
        foreach (System.Text.RegularExpressions.Match m in reTok.Matches(fuera)) if (!cabecera.Contains(m.Value)) cabecera.Add(m.Value);
        if (mDet.Success) foreach (System.Text.RegularExpressions.Match m in reTok.Matches(mDet.Groups[1].Value)) if (!banda.Contains(m.Value)) banda.Add(m.Value);
    }
    if (tokensExtra != null) foreach (var tk in tokensExtra) { if (detalle) { if (!banda.Contains(tk)) banda.Add(tk); } else if (!cabecera.Contains(tk)) cabecera.Add(tk); }
    Func<string, Dictionary<string, object>, long, long, string> val = (tok, fila, d, it) =>
    {
        string inner = tok.Substring(1, tok.Length - 2);
        if (inner == "QRPayload") return PayloadQrE(fila, d, it);
        if (inner == "DesgloseImpuestos") return DesgloseHtmlE(d);
        return System.Net.WebUtility.HtmlDecode(ResolverE(tok, fila, d, it));
    };
    var valores = new Dictionary<string, object>();
    foreach (var tk in cabecera) valores[tk] = val(tk, fila0, doc, itemDe(fila0));
    var lasFilas = new List<object>();
    foreach (var f in filas.Take(3))
    {
        var m = new Dictionary<string, object>();
        foreach (var tk in banda) m[tk] = val(tk, f, doc, itemDe(f));
        lasFilas.Add(m);
    }
    // Atributos con etiquetas (src="[LogoEmpresa]", style="color:[X]", data-qr="[QRPayload]"): su valor ya resuelto; en src, con la imagen incrustada
    var attrs = new Dictionary<string, object>();
    if (html != null && html != "")
    {
        string sinScripts2 = System.Text.RegularExpressions.Regex.Replace(html, @"<(script|style)\b[\s\S]*?</\1>", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        foreach (System.Text.RegularExpressions.Match m in System.Text.RegularExpressions.Regex.Matches(sinScripts2, "([A-Za-z\\-]+)\\s*=\\s*\"([^\"]*\\[[A-Za-z_][^\"]*)\""))
        {
            string orig = m.Groups[2].Value; if (attrs.ContainsKey(orig) || !reTok.IsMatch(orig)) continue;
            string r = orig;
            foreach (System.Text.RegularExpressions.Match tm in reTok.Matches(orig)) r = r.Replace(tm.Value, val(tm.Value, fila0, doc, itemDe(fila0)));
            if (m.Groups[1].Value.ToLowerInvariant() == "src")
            {
                string e = IncrustarImagenesE("src=\"" + r + "\"", baseDir ?? "");
                r = e.Substring(5, e.Length - 6);
            }
            attrs[orig] = r;
        }
    }
    return new Dictionary<string, object> { ["valores"] = valores, ["filas"] = lasFilas, ["nFilas"] = filas.Count, ["attrs"] = attrs };
}
// ---------- De dónde sale cada etiqueta del documento ----------
// Se lee la definición de la función de impresión (vwLBSDocDocumentPrint40-DocumentID) y se separa cada «expresión AS Alias» de su lista de columnas:
// así el Diseñador puede decir, por ejemplo, que [NumeroIdentificacion] sale de docDocumentItem.ProductKey.
static Dictionary<string, string> OrigenesColumnasE()
{
    var res = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    string def = "";
    try { def = S(ctx.Scalar("SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.[vwLBSDocDocumentPrint40-DocumentID]'))")); } catch { }
    if (def == "") return res;
    int i = System.Text.RegularExpressions.Regex.Match(def, @"\bSELECT\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase).Index + 6;
    int prof = 0; var item = new StringBuilder(); var items = new List<string>();
    for (; i < def.Length; i++)
    {
        char c = def[i];
        if (c == '\'') { item.Append(c); i++; while (i < def.Length) { item.Append(def[i]); if (def[i] == '\'') { if (i + 1 < def.Length && def[i + 1] == '\'') { i++; item.Append(def[i]); } else break; } i++; } continue; }
        if (c == '-' && i + 1 < def.Length && def[i + 1] == '-') { while (i < def.Length && def[i] != '\n') i++; continue; }
        if (c == '/' && i + 1 < def.Length && def[i + 1] == '*') { int fin = def.IndexOf("*/", i + 2, StringComparison.Ordinal); i = fin < 0 ? def.Length : fin + 1; continue; }
        if (c == '(') prof++; else if (c == ')') prof--;
        if (prof == 0)
        {
            if (c == ',') { items.Add(item.ToString()); item.Clear(); continue; }
            if ((c == 'F' || c == 'f') && i + 5 <= def.Length && string.Compare(def, i, "FROM", 0, 4, StringComparison.OrdinalIgnoreCase) == 0 && (i == 0 || char.IsWhiteSpace(def[i - 1])) && char.IsWhiteSpace(def[i + 4])) { items.Add(item.ToString()); break; }
        }
        item.Append(c);
    }
    foreach (var raw in items)
    {
        string t = System.Text.RegularExpressions.Regex.Replace(raw, @"\s+", " ").Trim(); if (t == "") continue;
        var m = System.Text.RegularExpressions.Regex.Match(t, @"^(.*?)\s+AS\s+\[?([A-Za-z_][A-Za-z0-9_]*)\]?$", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        string alias, expr;
        if (m.Success) { expr = m.Groups[1].Value.Trim(); alias = m.Groups[2].Value; }
        else { var m2 = System.Text.RegularExpressions.Regex.Match(t, @"^\[?([A-Za-z0-9_]+)\]?\.\[?([A-Za-z0-9_]+)\]?$"); if (!m2.Success) continue; expr = t; alias = m2.Groups[2].Value; }
        var ms = System.Text.RegularExpressions.Regex.Match(expr, @"^\[?([A-Za-z0-9_]+)\]?\.\[?([A-Za-z0-9_]+)\]?$");
        res[alias] = ms.Success ? ms.Groups[1].Value + "." + ms.Groups[2].Value : (expr.Length > 260 ? expr.Substring(0, 260) + "…" : expr);
    }
    return res;
}
// Para cada columna del documento: de dónde sale, el valor que tiene en este documento y si cambia por renglón
static Dictionary<string, object> InfoEtiquetasE(long doc)
{
    var origenes = OrigenesColumnasE(); var filas = CargarFilasE(doc);
    var res = new Dictionary<string, object>();
    if (filas.Count == 0) return new Dictionary<string, object> { ["columnas"] = res, ["hayDatos"] = false };
    foreach (var kv in filas[0])
    {
        string o = origenes.ContainsKey(kv.Key) ? origenes[kv.Key] : "";
        bool porRenglon = filas.Count > 1 && filas.Take(3).Select(f => FmtValorE(f.ContainsKey(kv.Key) ? f[kv.Key] : null)).Distinct().Count() > 1;
        if (!porRenglon && (o.IndexOf("docDocumentItem", StringComparison.OrdinalIgnoreCase) >= 0 || o.IndexOf("orgProduct", StringComparison.OrdinalIgnoreCase) >= 0)) porRenglon = true;
        res[kv.Key] = new Dictionary<string, object> { ["o"] = o, ["v"] = FmtValorE(kv.Value), ["r"] = porRenglon };
    }
    return new Dictionary<string, object> { ["columnas"] = res, ["hayDatos"] = true };
}
// HTML ya resuelto de UN documento a partir del TEXTO del formato (así se prueba lo que se está escribiendo, sin guardar)
static string ResolverFormatoE(string fuente, long doc, string baseDir)
{
    var protegidos = new List<string>();
    string html = System.Text.RegularExpressions.Regex.Replace(fuente, @"<(script|style)\b[\s\S]*?</\1>", mm => { protegidos.Add(mm.Value); return "@@BROSPROT" + (protegidos.Count - 1) + "@@"; }, System.Text.RegularExpressions.RegexOptions.IgnoreCase);
    var filas = CargarFilasE(doc);
    var fila0 = filas.Count > 0 ? filas[0] : new Dictionary<string, object>();
    Func<Dictionary<string, object>, long> itemDe = f => f.ContainsKey("DocumentItemID") && f["DocumentItemID"] != null && !(f["DocumentItemID"] is DBNull) ? Convert.ToInt64(f["DocumentItemID"]) : 0;
    long item0 = itemDe(fila0);
    var mDet = System.Text.RegularExpressions.Regex.Match(html, @"<DETAIL>(.*?)</DETAIL>", System.Text.RegularExpressions.RegexOptions.IgnoreCase | System.Text.RegularExpressions.RegexOptions.Singleline);
    var sb = new StringBuilder();
    if (mDet.Success)
    {
        sb.Append(ResolverE(html.Substring(0, mDet.Index), fila0, doc, item0));
        foreach (var f in filas) sb.Append(ResolverE(mDet.Groups[1].Value, f, doc, itemDe(f)));
        sb.Append(ResolverE(html.Substring(mDet.Index + mDet.Length), fila0, doc, item0));
    }
    else sb.Append(ResolverE(html, fila0, doc, item0));
    string outHtml = IncrustarImagenesE(sb.ToString(), baseDir ?? "");
    outHtml = System.Text.RegularExpressions.Regex.Replace(outHtml, "windows-1252", "utf-8", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
    if (outHtml.IndexOf("[QRPayload]", StringComparison.Ordinal) >= 0)
        outHtml = outHtml.Replace("[QRPayload]", System.Net.WebUtility.HtmlEncode(PayloadQrE(fila0, doc, item0)));
    if (outHtml.IndexOf("[QRBros]", StringComparison.Ordinal) >= 0)
        outHtml = System.Text.RegularExpressions.Regex.Replace(outHtml, @"<img[^>]*\[QRBros\][^>]*>", "").Replace("[QRBros]", "");
    if (outHtml.IndexOf("[DesgloseImpuestos]", StringComparison.Ordinal) >= 0)
        outHtml = outHtml.Replace("[DesgloseImpuestos]", DesgloseHtmlE(doc));
    for (int i = 0; i < protegidos.Count; i++) outHtml = outHtml.Replace("@@BROSPROT" + i + "@@", protegidos[i]);
    return outHtml;
}
static string LeerArchivoFormatoE(string archivo)
{
    byte[] bytes = File.ReadAllBytes(archivo);
    if (bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF) return new UTF8Encoding(false).GetString(bytes, 3, bytes.Length - 3);
    try { return new UTF8Encoding(false, true).GetString(bytes); } catch { return Encoding.GetEncoding(1252).GetString(bytes); }
}
static HashSet<string> respaldados = new HashSet<string>();                      // un solo respaldo por archivo y por sesión del editor



        public static object Despachar(string action, Dictionary<string, object> p)
        {
            object data = null; string err = null;
            {
                if (false) { }
                else if (action == "editorAbrir")
                {
                    long fid = Convert.ToInt64(p["formatId"]);
                    var fr = ctx.Query("SELECT f.ModuleID, f.FormatName, f.FileName, f.FormatIsDefault, ISNULL(m.ModuleName,'') AS Modulo FROM engModulePrintFormat f LEFT JOIN engModule m ON m.ModuleID=f.ModuleID WHERE f.PrintFormatID=" + fid);
                    if (fr.Count == 0) throw new Exception("El formato ya no existe.");
                    string arch = S(fr[0]["FileName"]); int mid = Convert.ToInt32(fr[0]["ModuleID"]);
                    if (!File.Exists(arch)) throw new Exception("No existe el archivo del formato:\n" + arch);
                    var docsMod = ctx.Query("SELECT TOP 40 d.DocumentID, ISNULL(d.FolioPrefix,'') AS Serie, ISNULL(CAST(d.Folio AS NVARCHAR(30)),'') AS Folio, ISNULL(be.CommercialName, be.OfficialName) AS Entidad, d.DateDocument " +
                        "FROM docDocument d LEFT JOIN orgBusinessEntity be ON be.BusinessEntityID=d.BusinessEntityID WHERE d.ModuleID=" + mid + " AND d.OwnedBusinessEntityID=" + owned + " AND d.DeletedOn IS NULL ORDER BY d.DocumentID DESC")
                        .Select(d => (object)o("id", L(d["DocumentID"]), "etiqueta", (S(d["Serie"]) + S(d["Folio"])).Trim() + " · " + S(d["Entidad"]) + " (ID " + L(d["DocumentID"]) + ")")).ToArray();
                    data = o("nombre", S(fr[0]["FormatName"]), "archivo", arch, "modulo", S(fr[0]["Modulo"]), "esDefault", B(fr[0]["FormatIsDefault"]), "html", LeerArchivoFormatoE(arch), "docs", docsMod);
                }
                else if (action == "editorVista")
                {
                    sinResolverE.Clear();
                    string htmlV = ""; string errV = null;
                    long docV = Convert.ToInt64(p["docId"]);
                    if (docV <= 0) errV = "No hay documentos de este tipo para probar el formato. Crea uno en Comercial y vuelve a abrir el editor.";
                    else
                    {
                        try { string archV = S(ctx.Scalar("SELECT FileName FROM engModulePrintFormat WHERE PrintFormatID=" + Convert.ToInt64(p["formatId"]))); htmlV = ResolverFormatoE(S(p["html"]), docV, Path.GetDirectoryName(archV)); }
                        catch (Exception exv) { errV = exv.Message; }
                        if (errV == null && htmlV.Length > 3000000) { errV = "El documento resuelto es demasiado grande para la vista previa (" + (htmlV.Length / 1024) + " KB)."; htmlV = ""; }
                    }
                    data = o("html", htmlV, "faltan", sinResolverE.OrderBy(x => x).ToArray(), "error", errV);
                }
                else if (action == "editorGuardar")
                {
                    long fid = Convert.ToInt64(p["formatId"]);
                    string arch = S(ctx.Scalar("SELECT FileName FROM engModulePrintFormat WHERE PrintFormatID=" + fid));
                    if (string.IsNullOrEmpty(arch)) throw new Exception("El formato ya no existe.");
                    string respaldo = "";
                    if (File.Exists(arch) && respaldados.Add(arch))
                    {
                        respaldo = arch + ".respaldo-" + DateTime.Now.ToString("yyyyMMdd-HHmmss");
                        File.Copy(arch, respaldo, true);
                    }
                    File.WriteAllText(arch, S(p["html"]), new UTF8Encoding(false));
                    data = o("ok", true, "respaldo", respaldo);
                }
                else if (action == "editorEtiquetas")
                {
                    var lst = new List<object>();
                    try
                    {
                        foreach (var c in ctx.Query("SELECT name FROM sys.columns WHERE object_id=OBJECT_ID('dbo.[vwLBSDocDocumentPrint40-DocumentID]') ORDER BY column_id"))
                            lst.Add(o("k", S(c["name"]), "d", "", "t", "col", "r", false, "c", false));
                    }
                    catch { }
                    foreach (var rf in ctx.Query("SELECT FieldRefKey, ISNULL(Description,'') AS Descr, ISNULL(Custom,0) AS Cus, CASE WHEN SQL LIKE '%{DocumentItemID}%' THEN 1 ELSE 0 END AS Renglon FROM engAddendaFieldRef WHERE DeletedOn IS NULL ORDER BY FieldRefKey"))
                        lst.Add(o("k", S(rf["FieldRefKey"]), "d", S(rf["Descr"]), "t", "ref", "r", Convert.ToInt32(rf["Renglon"]) == 1, "c", B(rf["Cus"])));
                    data = o("etiquetas", lst.ToArray());
                }
                else if (action == "disenoValores")
                {
                    long docD = Convert.ToInt64(p["docId"]);
                    string[] toks = null;
                    if (p.ContainsKey("tokens") && p["tokens"] is System.Collections.IEnumerable le && !(p["tokens"] is string)) toks = le.Cast<object>().Select(x => S(x)).ToArray();
                    string archD = S(ctx.Scalar("SELECT FileName FROM engModulePrintFormat WHERE PrintFormatID=" + Convert.ToInt64(p["formatId"])));
                    sinResolverE.Clear();
                    data = ValoresDisenoE(p.ContainsKey("html") ? S(p["html"]) : "", toks, p.ContainsKey("detalle") && B(p["detalle"]), docD, string.IsNullOrEmpty(archD) ? "" : Path.GetDirectoryName(archD));
                }
                else if (action == "disenoLogo")
                {
                    // Elegir una imagen y copiarla junto a los formatos (subcarpeta Imagenes): el formato la llama con una ruta relativa y el motor la incrusta al generar el PDF
                    using (var dlg = new OpenFileDialog { Filter = "Imágenes (*.png;*.jpg;*.jpeg;*.gif;*.svg;*.bmp)|*.png;*.jpg;*.jpeg;*.gif;*.svg;*.bmp", Title = "Elige el logo o la imagen" })
                    {
                        if (dlg.ShowDialog() != DialogResult.OK) data = o("cancel", true);
                        else
                        {
                            string dirImg = Path.Combine(carpetaFormatos(), "Imagenes"); Directory.CreateDirectory(dirImg);
                            string nom = System.Text.RegularExpressions.Regex.Replace(Path.GetFileNameWithoutExtension(dlg.FileName), @"[^A-Za-z0-9_\-]", "_"), ext = Path.GetExtension(dlg.FileName).ToLowerInvariant();
                            string dest = Path.Combine(dirImg, nom + ext); int k = 2;
                            while (File.Exists(dest) && !File.ReadAllBytes(dest).SequenceEqual(File.ReadAllBytes(dlg.FileName))) dest = Path.Combine(dirImg, nom + "_" + (k++) + ext);
                            if (!File.Exists(dest)) File.Copy(dlg.FileName, dest);
                            string mime = ext == ".svg" ? "image/svg+xml" : ext == ".jpg" ? "image/jpeg" : "image/" + ext.TrimStart('.');
                            data = o("ruta", "Imagenes/" + Path.GetFileName(dest), "vista", "data:" + mime + ";base64," + Convert.ToBase64String(File.ReadAllBytes(dest)));
                        }
                    }
                }
                else if (action == "esquemaTablas")
                {
                    var populares = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "docDocument", "docDocumentItem", "docDocumentTaxDetail", "docDocumentPayment", "docDocumentCFD", "docDocumentExt", "docDocumentExtra", "docDocumentPaymentAgenda",
                        "orgBusinessEntity", "orgBusinessEntityMainInfo", "orgCustomer", "orgSupplier", "orgProduct", "orgProductKardex", "orgDepot", "orgCostCenter", "engPaymentTerm", "engTaxType", "engUser", "docFinancialOperation", "docDocumentLot", "docDocumentSerialNumber" };
                    var tb = ctx.Query("SELECT name, 'T' AS tipo FROM sys.tables WHERE name NOT LIKE 'zz%' AND name NOT LIKE 'Import%' AND name NOT LIKE '[_]%' AND (name LIKE 'doc%' OR name LIKE 'org%' OR name LIKE 'eng%' OR name LIKE 'acc%') " +
                        "UNION ALL SELECT name, 'V' FROM sys.views WHERE name LIKE 'vw%' AND name NOT LIKE '%-%' ORDER BY name")
                        .Select(r => (object)o("t", S(r["name"]), "p", populares.Contains(S(r["name"])), "v", S(r["tipo"]) == "V")).ToArray();
                    data = o("tablas", tb);
                }
                else if (action == "esquemaColumnas")
                {
                    string tabla = S(p["tabla"]);
                    if (!System.Text.RegularExpressions.Regex.IsMatch(tabla, "^[A-Za-z0-9_]+$")) throw new Exception("Nombre de tabla no válido.");
                    var cols = ctx.Query("SELECT c.name, ty.name AS tipo FROM sys.columns c JOIN sys.types ty ON ty.user_type_id=c.user_type_id WHERE c.object_id=OBJECT_ID('dbo.[" + tabla + "]') ORDER BY c.column_id");
                    if (cols.Count == 0) throw new Exception("La tabla no existe.");
                    Func<string, HashSet<string>> colsDe = t2 => new HashSet<string>(ctx.Query("SELECT name FROM sys.columns WHERE object_id=OBJECT_ID('dbo.[" + t2 + "]')").Select(r => S(r["name"])), StringComparer.OrdinalIgnoreCase);
                    var enDoc = colsDe("docDocument"); var enItem = colsDe("docDocumentItem");
                    var nombres = cols.Select(c => S(c["name"])).ToList();
                    var rel = new List<object>();
                    // «Mismo valor que el documento / que la partida»: cualquier columna que la tabla comparta con docDocument o docDocumentItem sirve de enlace
                    foreach (var n in nombres)
                    {
                        if (n == "DocumentID") rel.Add(o("col", n, "via", "doc", "texto", "es de este documento (DocumentID)"));
                        else if (n == "DocumentItemID" && tabla != "docDocumentItem") rel.Add(o("col", n, "via", "item", "texto", "es de esta partida (DocumentItemID)"));
                        else if (n.EndsWith("ID") && enDoc.Contains(n) && n != "CreatedBy" && n != "DeletedBy" && n != "UserID" && !(tabla == "docDocument" && n == "DocumentID")) rel.Add(o("col", n, "via", "docCol", "texto", n + " es el mismo que el del documento"));
                        else if (n.EndsWith("ID") && enItem.Contains(n) && n != "CreatedBy" && n != "DeletedBy" && n != "UserID" && n != "DocumentID" && n != "DocumentItemID") rel.Add(o("col", n, "via", "itemCol", "texto", n + " es el mismo que el de la partida"));
                    }
                    if (tabla == "docDocument") rel.Add(o("col", "DocumentID", "via", "doc", "texto", "es este documento"));
                    if (tabla == "docDocumentItem") rel.Add(o("col", "DocumentItemID", "via", "item", "texto", "es esta partida"));
                    data = o("columnas", cols.Select(c => (object)o("n", S(c["name"]), "t", S(c["tipo"]))).ToArray(), "relaciones", rel.ToArray(), "borrado", nombres.Contains("DeletedOn"));
                }
                else if (action == "refProbar")
                {
                    string sql = S(p["sql"]); long dId = Convert.ToInt64(p["docId"]); long iId = p.ContainsKey("itemId") ? Convert.ToInt64(p["itemId"]) : 0;
                    if (iId == 0) { try { iId = Convert.ToInt64(ctx.Scalar("SELECT ISNULL(MIN(DocumentItemID),0) FROM docDocumentItem WHERE DocumentID=" + dId + " AND DeletedOn IS NULL")); } catch { } }
                    if (System.Text.RegularExpressions.Regex.IsMatch(sql, @"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|EXEC|EXECUTE|MERGE|CREATE)\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase)) throw new Exception("La referencia solo puede leer datos (SELECT).");
                    string ev = null, er = null;
                    try { var rv = ctx.Scalar(sql.Replace("{DocumentID}", dId.ToString()).Replace("{DocumentItemID}", iId.ToString())); ev = rv == null || rv is DBNull ? "" : (rv is DateTime rd ? rd.ToString("dd/MM/yyyy") : Convert.ToString(rv, ciE)); }
                    catch (Exception exr) { er = exr.Message; }
                    data = o("valor", ev, "error", er);
                }
                else if (action == "refGuardar")
                {
                    string key = S(p["key"]).Trim(), sqlR = S(p["sql"]), desc = S(p["desc"]);
                    if (!System.Text.RegularExpressions.Regex.IsMatch(key, "^[A-Za-z_][A-Za-z0-9_]*$")) throw new Exception("El nombre solo puede llevar letras, números y guion bajo, y no empezar con número.");
                    if (System.Text.RegularExpressions.Regex.IsMatch(sqlR, @"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|EXEC|EXECUTE|MERGE|CREATE)\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase)) throw new Exception("La referencia solo puede leer datos (SELECT).");
                    int colExiste = Convert.ToInt32(ctx.Scalar("SELECT COUNT(*) FROM sys.columns WHERE object_id=OBJECT_ID('dbo.[vwLBSDocDocumentPrint40-DocumentID]') AND name=N'" + key.Replace("'", "''") + "'"));
                    if (colExiste > 0) throw new Exception("«" + key + "» ya es una columna del documento: elige otro nombre.");
                    int ya = Convert.ToInt32(ctx.Scalar("SELECT COUNT(*) FROM engAddendaFieldRef WHERE FieldRefKey=N'" + key.Replace("'", "''") + "' AND DeletedOn IS NULL AND ISNULL(Custom,0)=0"));
                    if (ya > 0) throw new Exception("«" + key + "» ya existe en el Diccionario de referencia de Comercial (no es una referencia propia): elige otro nombre.");
                    using (var cn = ctx.OpenConn()) using (var cm = cn.CreateCommand())
                    {
                        cm.CommandText = "IF EXISTS (SELECT 1 FROM engAddendaFieldRef WHERE FieldRefKey=@k AND DeletedOn IS NULL AND Custom=1) UPDATE engAddendaFieldRef SET SQL=@s, Description=@d WHERE FieldRefKey=@k AND DeletedOn IS NULL AND Custom=1 " +
                            "ELSE INSERT INTO engAddendaFieldRef (FieldRefKey,SQL,Description,Custom,CreatedOn,CreatedBy) VALUES (@k,@s,@d,1,GETDATE(),@by)";
                        cm.Parameters.AddWithValue("@k", key); cm.Parameters.AddWithValue("@s", sqlR); cm.Parameters.AddWithValue("@d", desc == "" ? (object)("BrosLMV: " + key) : desc); cm.Parameters.AddWithValue("@by", userId);
                        cm.ExecuteNonQuery();
                    }
                    sqlRefsE = null; cacheRefE.Clear(); refsExistenE.Clear();
                    data = o("ok", true);
                }
                else if (action == "formatosListado")
                {
                    var lf = ctx.Query("SELECT f.PrintFormatID, f.ModuleID, ISNULL(m.ModuleName,'') AS Modulo, f.FormatName, ISNULL(f.FormatIsDefault,0) AS Def, f.FileName FROM engModulePrintFormat f LEFT JOIN engModule m ON m.ModuleID=f.ModuleID " +
                        "WHERE ISNULL(f.FileName,'')<>'' AND (f.FileName LIKE '%.htm' OR f.FileName LIKE '%.html') ORDER BY m.ModuleName, f.FormatIsDefault DESC, f.FormatName")
                        .Select(r => (object)o("id", L(r["PrintFormatID"]), "modulo", S(r["Modulo"]), "nombre", S(r["FormatName"]), "def", B(r["Def"]), "archivo", S(r["FileName"]))).ToArray();
                    data = o("formatos", lf);
                }
                else if (action == "etiquetasInfo")
                {
                    sinResolverE.Clear();
                    data = InfoEtiquetasE(Convert.ToInt64(p["docId"]));
                }
                else if (action == "refDetalle")
                {
                    string kd = S(p["k"]); long dd = Convert.ToInt64(p["docId"]); long itd = 0;
                    try { itd = Convert.ToInt64(ctx.Scalar("SELECT ISNULL(MIN(DocumentItemID),0) FROM docDocumentItem WHERE DocumentID=" + dd + " AND DeletedOn IS NULL")); } catch { }
                    var rr = ctx.Query("SELECT SQL, ISNULL(Description,'') AS Descr, ISNULL(Custom,0) AS Cus FROM engAddendaFieldRef WHERE FieldRefKey=N'" + kd.Replace("'", "''") + "' AND DeletedOn IS NULL");
                    string sqlD = rr.Count > 0 ? S(rr[0]["SQL"]) : ""; string valD = "", errD = null;
                    if (sqlD.Trim() != "")
                    {
                        try { var vv = ctx.Scalar(sqlD.Replace("{DocumentID}", dd.ToString()).Replace("{DocumentItemID}", itd.ToString())); valD = vv == null || vv is DBNull ? "" : (vv is DateTime vd ? vd.ToString("dd/MM/yyyy") : Convert.ToString(vv, ciE)); }
                        catch (Exception exd) { errD = exd.Message; }
                    }
                    data = o("sql", sqlD, "valor", valD, "error", errD, "propia", rr.Count > 0 && B(rr[0]["Cus"]), "desc", rr.Count > 0 ? S(rr[0]["Descr"]) : "");
                }
                else if (action == "refEjecutar")
                {
                    // Ejecuta una consulta de LECTURA para probarla con el documento elegido (muestra las primeras filas)
                    string sqlE = S(p["sql"]).Trim().TrimEnd(';').Trim(); long dE = Convert.ToInt64(p["docId"]); long iE = p.ContainsKey("itemId") ? Convert.ToInt64(p["itemId"]) : 0;
                    int maxF = p.ContainsKey("max") ? Convert.ToInt32(p["max"]) : 50;
                    if (iE == 0) { try { iE = Convert.ToInt64(ctx.Scalar("SELECT ISNULL(MIN(DocumentItemID),0) FROM docDocumentItem WHERE DocumentID=" + dE + " AND DeletedOn IS NULL")); } catch { } }
                    string sinCom = System.Text.RegularExpressions.Regex.Replace(sqlE, @"--[^\n]*|/\*[\s\S]*?\*/", " ").Trim();
                    if (!System.Text.RegularExpressions.Regex.IsMatch(sinCom, @"^(SELECT|WITH)\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase)) throw new Exception("La consulta debe empezar con SELECT (o WITH).");
                    if (sinCom.Contains(";")) throw new Exception("Escribe una sola consulta (sin «;» en medio).");
                    if (System.Text.RegularExpressions.Regex.IsMatch(sinCom, @"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|EXEC|EXECUTE|MERGE|CREATE|GRANT|REVOKE|BACKUP|RESTORE|SHUTDOWN|INTO|OPENROWSET|OPENQUERY|xp_\w*)\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase)) throw new Exception("La consulta solo puede leer datos (SELECT).");
                    var colsE = new List<string>(); var filasE = new List<object>(); int totalE = 0; string errE = null;
                    try
                    {
                        using (var cn = ctx.OpenConn()) using (var cm = cn.CreateCommand())
                        {
                            cm.CommandText = "SET NOCOUNT ON; SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; " + sqlE.Replace("{DocumentID}", dE.ToString()).Replace("{DocumentItemID}", iE.ToString()); cm.CommandTimeout = 20;
                            using (var rd = cm.ExecuteReader())
                            {
                                for (int ci = 0; ci < rd.FieldCount; ci++) colsE.Add(rd.GetName(ci));
                                while (rd.Read()) { totalE++; if (filasE.Count < maxF) { var fe = new object[rd.FieldCount]; for (int ci = 0; ci < rd.FieldCount; ci++) { var vv = rd.GetValue(ci); fe[ci] = vv == null || vv is DBNull ? null : (vv is DateTime vd ? vd.ToString("dd/MM/yyyy HH:mm") : Convert.ToString(vv, ciE)); } filasE.Add(fe); } if (totalE >= 5000) { cm.Cancel(); break; } }
                            }
                        }
                    }
                    catch (Exception exq) { errE = exq.Message; }
                    data = o("columnas", colsE.ToArray(), "filas", filasE.ToArray(), "total", totalE, "error", errE);
                }
                else throw new Exception("Acción desconocida: " + action);
            }
            if (err != null) throw new Exception(err);
            return data;
        }
    }
}
